In [9]:
import numpy as np
from mpl_toolkits import mplot3d
import scipy.sparse as spa
import scipy.sparse.linalg as spalg
from scipy import interpolate
import matplotlib.pyplot as plt

In [10]:
N = 101
R = 0.1
step = R/(N-1)
d = step*(N-1)

## In order to solve the laplace, we're going to solve the following problem with Dirichlet boundary conditions

## $A\vec{u} + \vec{b} = 0$

# Setting up your Laplace operator ($A$)

In [25]:
lap = np.zeros((N*N,N*N))
lap.shape

(10201, 10201)

In [26]:
def idx(i_rho, i_z, N): 
    return i_rho + (i_z)*N

In [48]:
for izy in range(1,N-1): 
    irhoy=1
    lap[idx(irhoy,izy,N), idx(irhoy,izy,N)] = -6
    lap[idx(irhoy,izy,N), idx(irhoy+1,izy,N)] = 4
    lap[idx(irhoy,izy,N), idx(irhoy,izy-1,N)] = 1
    lap[idx(irhoy,izy,N), idx(irhoy,izy+1,N)] = 1
    for irhoy in range(1,N-1): 
        n =(irhoy);
        lap[idx(irhoy,izy,N), idx(irhoy,izy,N)] = -4
        lap[idx(irhoy,izy,N), idx(irhoy-1,izy,N)] = 1-.5/(float(n))
        lap[idx(irhoy,izy,N), idx(irhoy+1,izy,N)] = 1+.5/(float(n))
        lap[idx(irhoy,izy,N), idx(irhoy,izy-1,N)] = 1
        lap[idx(irhoy, izy,N),idx(irhoy,izy+1,N)] = 1
        
lap = lap/(step**2)
        

In [50]:
lap[]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
V = np.zeros((N*N,1))

In [111]:
## Setting the boundary conditions
vtop = 1
vbot = -1

V[idx(range(1,N),0,N)] = vbot
V[idx(range(1,N),N,N)] = vtop
f_V = interpolate.interp1d([1,N],[vbot,vtop])
#plt.plot(range(1,N), f_V(range(1,N)))
V_start = f_V(range(0,N))
for i in range(0,N):
    V[idx(N,i,N)] =V_start[i]

ValueError: A value in x_new is below the interpolation range.

array([1.])

array([-1.  , -0.98, -0.96, -0.94, -0.92, -0.9 , -0.88, -0.86, -0.84,
       -0.82, -0.8 , -0.78, -0.76, -0.74, -0.72, -0.7 , -0.68, -0.66,
       -0.64, -0.62, -0.6 , -0.58, -0.56, -0.54, -0.52, -0.5 , -0.48,
       -0.46, -0.44, -0.42, -0.4 , -0.38, -0.36, -0.34, -0.32, -0.3 ,
       -0.28, -0.26, -0.24, -0.22, -0.2 , -0.18, -0.16, -0.14, -0.12,
       -0.1 , -0.08, -0.06, -0.04, -0.02,  0.  ,  0.02,  0.04,  0.06,
        0.08,  0.1 ,  0.12,  0.14,  0.16,  0.18,  0.2 ,  0.22,  0.24,
        0.26,  0.28,  0.3 ,  0.32,  0.34,  0.36,  0.38,  0.4 ,  0.42,
        0.44,  0.46,  0.48,  0.5 ,  0.52,  0.54,  0.56,  0.58,  0.6 ,
        0.62,  0.64,  0.66,  0.68,  0.7 ,  0.72,  0.74,  0.76,  0.78,
        0.8 ,  0.82,  0.84,  0.86,  0.88,  0.9 ,  0.92,  0.94,  0.96,
        0.98,  1.  ])

In [91]:
V(idx(N,range(1,N+1),N)).shape

SyntaxError: invalid syntax (<ipython-input-91-7894a3eea154>, line 1)

SyntaxError: invalid syntax (<ipython-input-71-055320a0773b>, line 1)

SyntaxError: illegal target for annotation (<ipython-input-88-fb216bd7f62d>, line 1)